# Generated by Django 3.2.7 on 2021-10-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertiseWithUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('phone_number', models.BigIntegerField()),
                ('banner', models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three')], default='1', max_length=40)),
                ('banner_img', models.ImageField(upload_to='')),
                ('redirection_link', models.URLField()),
            ],
        ),
    ]
