# Generated by Django 3.2.7 on 2021-10-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisewithus',
            name='banner_img',
            field=models.FileField(upload_to=''),
        ),
    ]
