# Generated by Django 3.2.7 on 2021-10-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0002_alter_advertisewithus_banner_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisewithus',
            name='banner_img',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='advertisewithus',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='advertisewithus',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='advertisewithus',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
