# Generated by Django 3.2.7 on 2021-10-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=200, unique='True')),
                ('coin_name', models.CharField(max_length=100, unique='True')),
                ('coin_logo', models.ImageField(blank='True', null='True', upload_to='pics')),
            ],
        ),
    ]
