# Generated by Django 3.2.7 on 2021-10-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('user_email', models.EmailField(max_length=254, null=True, unique=True)),
                ('user_password', models.TextField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CreatePage',
        ),
    ]
