# Generated by Django 3.2.7 on 2021-10-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20211018_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adduser',
            old_name='user_password',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='adduser',
            name='user_email',
        ),
        migrations.AddField(
            model_name='adduser',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
