# Generated by Django 3.2.7 on 2021-10-19 18:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20211019_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='adduser',
            name='created_dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
