# Generated by Django 3.2.7 on 2021-10-20 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_adduser_created_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adduser',
            name='created_dt',
            field=models.DateTimeField(db_column='Created Date', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='adduser',
            name='email',
            field=models.EmailField(db_column='email', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='adduser',
            name='password',
            field=models.TextField(db_column='password', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adduser',
            name='username',
            field=models.CharField(db_column='username', max_length=100, null=True),
        ),
    ]
