# Generated by Django 3.2.7 on 2021-10-27 09:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_adduser_confirm_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateNewPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(db_column='page name', max_length=200, null=True)),
                ('coin_name', models.CharField(db_column='coin name', max_length=100, null=True)),
                ('coin_logo', models.ImageField(blank=True, null=True, upload_to='media/coin_logo/')),
                ('created_by', models.CharField(max_length=200, null=True)),
                ('created_dt', models.DateTimeField(db_column='Created Date', default=django.utils.timezone.now)),
            ],
        ),
    ]
