# Generated by Django 3.2.7 on 2021-10-29 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20211027_1525'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddUser',
        ),
    ]
