# Generated by Django 3.2.7 on 2021-10-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about1', models.TextField(db_column='about_us_1', max_length=3000)),
                ('about2', models.TextField(db_column='about_us_2', max_length=3000)),
            ],
            options={
                'verbose_name_plural': 'About Us',
                'db_table': 'about_us',
            },
        ),
    ]
