# Generated by Django 3.2.7 on 2021-10-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='image1',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='image2',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
