# Generated by Django 3.2.7 on 2021-10-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.IntegerField(blank=True, db_column='otp', null=True, verbose_name='OTP'),
        ),
    ]
