# Generated by Django 3.2.7 on 2021-10-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0006_alter_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, db_column='address', null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(blank=True, db_column='fullname', max_length=250, null=True, verbose_name='FullName'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_no',
            field=models.IntegerField(null=True),
        ),
    ]
