# Generated by Django 3.2.7 on 2021-10-21 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0008_auto_20211020_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fullname',
            new_name='full_name',
        ),
    ]
