# Generated by Django 3.2.7 on 2021-10-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0010_alter_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_dt',
            field=models.DateTimeField(auto_now=True, db_column='Created Date'),
        ),
    ]
