# Generated by Django 3.2.7 on 2021-10-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0012_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='update_dt',
            field=models.DateTimeField(auto_now=True, db_column='update_dt', null=True, verbose_name='Update Dt'),
        ),
    ]
