# Generated by Django 3.2.7 on 2021-10-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0013_alter_user_update_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='update_dt',
            field=models.DateTimeField(blank=True, db_column='update_dt', null=True, verbose_name='Update Dt'),
        ),
    ]
