# Generated by Django 3.2.7 on 2021-10-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique='True')),
                ('email', models.EmailField(max_length=200, unique='True')),
                ('phone', models.IntegerField(max_length=10, unique='True')),
                ('comment', models.TextField(max_length=500)),
            ],
        ),
    ]
