# Generated by Django 3.2.7 on 2021-10-09 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contactus_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='username',
            new_name='name',
        ),
    ]
