# Generated by Django 3.2.7 on 2021-10-19 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20211010_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='email',
            new_name='user_email',
        ),
    ]
