# Generated by Django 3.2.7 on 2021-10-19 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_rename_email_contactus_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='user_email',
            new_name='email',
        ),
    ]
