# Generated by Django 3.2.7 on 2021-10-19 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_rename_user_email_contactus_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='email',
            new_name='user_email',
        ),
    ]
